package com.shenxy.smartapploader.greendao.dao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.shenxy.smartapploader.greendao.dao.LightAppAuth.LightAppAuthItem;
import com.shenxy.smartapploader.greendao.dao.download.TWDownloadFilesEntity;

import com.shenxy.smartapploader.greendao.dao.db.LightAppAuthItemDao;
import com.shenxy.smartapploader.greendao.dao.db.TWDownloadFilesEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lightAppAuthItemDaoConfig;
    private final DaoConfig tWDownloadFilesEntityDaoConfig;

    private final LightAppAuthItemDao lightAppAuthItemDao;
    private final TWDownloadFilesEntityDao tWDownloadFilesEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lightAppAuthItemDaoConfig = daoConfigMap.get(LightAppAuthItemDao.class).clone();
        lightAppAuthItemDaoConfig.initIdentityScope(type);

        tWDownloadFilesEntityDaoConfig = daoConfigMap.get(TWDownloadFilesEntityDao.class).clone();
        tWDownloadFilesEntityDaoConfig.initIdentityScope(type);

        lightAppAuthItemDao = new LightAppAuthItemDao(lightAppAuthItemDaoConfig, this);
        tWDownloadFilesEntityDao = new TWDownloadFilesEntityDao(tWDownloadFilesEntityDaoConfig, this);

        registerDao(LightAppAuthItem.class, lightAppAuthItemDao);
        registerDao(TWDownloadFilesEntity.class, tWDownloadFilesEntityDao);
    }
    
    public void clear() {
        lightAppAuthItemDaoConfig.getIdentityScope().clear();
        tWDownloadFilesEntityDaoConfig.getIdentityScope().clear();
    }

    public LightAppAuthItemDao getLightAppAuthItemDao() {
        return lightAppAuthItemDao;
    }

    public TWDownloadFilesEntityDao getTWDownloadFilesEntityDao() {
        return tWDownloadFilesEntityDao;
    }

}
