package com.shenxy.smartapploader.greendao.dao.download;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TWDownloadFiles.
 */
public class TWDownloadFilesEntity {

    private Long id;
    private String uri;
    private String alt;
    private String method;
    private String mime_type;
    private Integer http_status;
    private Integer file_status;
    private Long start_time;
    private Long update_time;
    private Long length;
    private Long current_length;
    private String file_md5;
    private String path;
    private String file_full_name;
    private String file_name;
    private String file_ext_name;
    private String file_uncompressed_path;
    private String info;

    // KEEP FIELDS - put your custom fields here

    public enum FILE_STATUS {

        FILE_STATUS_CONNECT_ERROR(0),
        FILE_STATUS_CREATED(2),
        FILE_STATUS_DOWNLOADING(3),
        FILE_STATUS_DOWNLOADED(4),
        FILE_STATUS_DOWNLOAD_FAILED(5),
        FILE_STATUS_UNCOMPRESSED(6),
        FILE_STATUS_DELETED(7);

        int value;

        FILE_STATUS(int v) {
            value = v;
        }

        public Integer value() {
            return value;
        }
    }
    // KEEP FIELDS END

    public TWDownloadFilesEntity() {
    }

    public TWDownloadFilesEntity(Long id) {
        this.id = id;
    }

    public TWDownloadFilesEntity(Long id, String uri, String alt, String method, String mime_type, Integer http_status, Integer file_status, Long start_time, Long update_time, Long length, Long current_length, String file_md5, String path, String file_full_name, String file_name, String file_ext_name, String file_uncompressed_path, String info) {
        this.id = id;
        this.uri = uri;
        this.alt = alt;
        this.method = method;
        this.mime_type = mime_type;
        this.http_status = http_status;
        this.file_status = file_status;
        this.start_time = start_time;
        this.update_time = update_time;
        this.length = length;
        this.current_length = current_length;
        this.file_md5 = file_md5;
        this.path = path;
        this.file_full_name = file_full_name;
        this.file_name = file_name;
        this.file_ext_name = file_ext_name;
        this.file_uncompressed_path = file_uncompressed_path;
        this.info = info;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getAlt() {
        return alt;
    }

    public void setAlt(String alt) {
        this.alt = alt;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getMime_type() {
        return mime_type;
    }

    public void setMime_type(String mime_type) {
        this.mime_type = mime_type;
    }

    public Integer getHttp_status() {
        return http_status;
    }

    public void setHttp_status(Integer http_status) {
        this.http_status = http_status;
    }

    public Integer getFile_status() {
        return file_status;
    }

    public void setFile_status(Integer file_status) {
        this.file_status = file_status;
    }

    public Long getStart_time() {
        return start_time;
    }

    public void setStart_time(Long start_time) {
        this.start_time = start_time;
    }

    public Long getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }

    public Long getLength() {
        return length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public Long getCurrent_length() {
        return current_length;
    }

    public void setCurrent_length(Long current_length) {
        this.current_length = current_length;
    }

    public String getFile_md5() {
        return file_md5;
    }

    public void setFile_md5(String file_md5) {
        this.file_md5 = file_md5;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getFile_full_name() {
        return file_full_name;
    }

    public void setFile_full_name(String file_full_name) {
        this.file_full_name = file_full_name;
    }

    public String getFile_name() {
        return file_name;
    }

    public void setFile_name(String file_name) {
        this.file_name = file_name;
    }

    public String getFile_ext_name() {
        return file_ext_name;
    }

    public void setFile_ext_name(String file_ext_name) {
        this.file_ext_name = file_ext_name;
    }

    public String getFile_uncompressed_path() {
        return file_uncompressed_path;
    }

    public void setFile_uncompressed_path(String file_uncompressed_path) {
        this.file_uncompressed_path = file_uncompressed_path;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
